### ISSUE TITLE
Reduce size of npm package

### ISSUE THREAD

**Issue by scottnonnenberg** [evcohen/eslint-plugin-jsx-a11y#107]
Based on my analysis, v1.2.3 of `eslint-plugin-jsx-a11y` is 992k on disk! And this is because it includes `docs/`, `tests/`, and `src/` in addition to the `lib/` directory, the only one needed for the node module to run.

**Comment by evcohen** [comment]
see [this discussion](https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/108)
