### ISSUE TITLE
[Q] Is having a form without <form> valid?

### ISSUE THREAD

**Issue by tleunen** [evcohen/eslint-plugin-jsx-a11y#110]
In term of a11y, is having a form without a `<form>` tag valid? If you have labels for each input and a custom button with an `onClick` event, instead of having a `<form onSubmit={sth}>`?

Without the form tag, it seems the user should also handle a <enter> key down. But is there anything else?

**Comment by ljharb** [comment]
Why would you want to omit the `<form>` tag tho?

**Comment by tleunen** [comment]
No idea.. ;) With SPA, it's easy to do a form without using any `<form>`... 

But then, is it valid with `<form onSubmit={}>` or do we still need to set an action and method?

**Comment by ljharb** [comment]
I'd think it's still valid; but for accessibility, you'd want to set an action and method, and let it be submittable without JS.

If your SPA isn't accessible, that's a separate problem :-)

**Comment by tleunen** [comment]
An SPA without javascript... hmm... :D
