### ISSUE TITLE
v3.0.0?

### ISSUE THREAD

**Issue by ljharb** [evcohen/eslint-plugin-jsx-a11y#114]
I'm seeing a v3.0.0 sometimes published and sometimes not - but there's no tag in the repo.

Was this a control-c'd publish, perhaps? Can it be unpublished, or a v3.0.1 published?

**Comment by evcohen** [comment]
hm, i published, then unpublished immediately because im working on more breaking changes that was trying to get into this release. i can republish v3.0.0 and hold off on this update for a v4.0.0, though

**Comment by evcohen** [comment]
[v3.0.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v3.0.0) published, let me know if this works.
