### ISSUE TITLE
Error in Atom opening .js file

### ISSUE THREAD

**Issue by chemitaxis** [evcohen/eslint-plugin-jsx-a11y#115]
> Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
> 	Value "" is the wrong type.
> Referenced from: airbnb

Any ideas? Thanks

**Comment by cooperka** [comment]
I'm getting the same error -- I assume it's due to the version published on npm being out of date. The latest version here on GitHub is [v3.0.1](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v3.0.1), but on npm it's only [2.2.3](https://www.npmjs.com/package/eslint-plugin-jsx-a11y). Hopefully it's updated soon, but in the meantime you can point your npm dependency here!

**Comment by chemitaxis** [comment]
I have solved cleaning cache in npm and don't using yarn

**Comment by ljharb** [comment]
@cooperka the real fix is using the install command in the airbnb package's readme, so that you have the proper peer deps, instead of blindly upgrading. `npm ls` would have told you that v3 of this package was incompatible.

**Comment by chemitaxis** [comment]
Yes, exactly, this one: 

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

**Comment by cooperka** [comment]
Thanks @ljharb, that works even better! I checked the [release notes](https://github.com/airbnb/javascript/releases) before upgrading to v13 of course, but unfortunately there were none, so I had no idea I was supposed to run that command. Cheers!

**Comment by ljharb** [comment]
@cooperka the release notes for any repo are always in a changelog file - the page on Github is never guaranteed to be filled out for any repo. https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md and https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md are the relevant ones.
