### ISSUE TITLE
[aria-proptypes] issue with aria-invalid attribute

### ISSUE THREAD

**Issue by slek22** [evcohen/eslint-plugin-jsx-a11y#127]
Hi !

I noticed a strange behavior with the aria-proptypes rule.
When I set and aria-invalid attribute with a boolean i got this eslint error : 

`The value for aria-invalid must be a single token from the following: grammar,false,spelling,true.`

With some additional tests I could see that with the first letter of the value in uppercase it's ok for the plugin...

aria-invalid="true"     -> not pass
aria-invalid="True"    -> pass
aria-invalid="false"    -> not pass
aria-invalid="False"   -> pass

Is it easily fixable ?

**Comment by ljharb** [comment]
Recently fixed by #126.

**Comment by slek22** [comment]
oups sorry
