### ISSUE TITLE
htmlFor versus for?

### ISSUE THREAD

**Issue by jasonday** [evcohen/eslint-plugin-jsx-a11y#132]
Isn't ` htmlfor` is only recognized by IE8 if it's in Compatibility Mode. In Standards Mode, it ignores the `htmlfor` attribute. In both modes, `for` works properly. Shouldn't `htmlFor` be `for`, or what am I missing?

**Comment by lencioni** [comment]
https://facebook.github.io/react/docs/dom-elements.html#htmlfor

> Since `for` is a reserved word in JavaScript, React elements use `htmlFor` instead.

If you use `htmlFor` on your React element, `for` will end up in the DOM.

**Comment by jasonday** [comment]
Thanks! Sorry for the superfluous issue.
