### ISSUE TITLE
Any interest in standardized commit message formatting and/or CHANGELOG generation?

### ISSUE THREAD

**Issue by ryanvanoss** [evcohen/eslint-plugin-jsx-a11y#145]
This could be as simple as making the repo [commitizen friendly](https://commitizen.github.io/cz-cli/#making-your-repo-commitizen-friendly) or as deep as integrating [semantic-release](https://github.com/semantic-release/semantic-release), or pretty much anywhere in-between. If you're interested, I'll take it on.

**Comment by ljharb** [comment]
I'm very -1 on semantic-release - automating change log generation is nice - but enforced commit message conventions are pretty annoying for contributors.

**Comment by ryanvanoss** [comment]
I think there's a lot more to win by introducing a formal message syntax. Commitizen, and it's use of Inquirer, make it very simple to get the formatting right without changing your typical workflow (`git cz` instead of `git commit`). We're talking about something that could automate the workflow from commit to version bump to CHANGELOG generation to release, which to me vastly outweighs the potential annoyance it may bring to authoring a commit message. Outside of the improvements to the CI workflow that semantic-release could bring, simply adding some focus on the message itself naturally tends to nudge collaborators toward making meaningful, atomic commits. So while I hear you that it could be initially annoying to some users, I can't see that as a reason to disregard all the other benefits it would bring.

**Comment by ljharb** [comment]
Just sharing the experience of trying to make PRs to projects that have CI-enforced commit message conventions - it's pretty frustrating, and lots of users don't know git well enough to know how to fix it easily.

**Comment by ryanvanoss** [comment]
Yeah, I hear ya.

If that's a big concern, we should be able to mitigate it with a simple client side hook. This would prevent the bad messages from ever making it in, so people won't need to worry about fixing a bad message.

**Comment by ljharb** [comment]
Clientside hooks can't be installed except with explicit client cooperation; they don't work on Github's UI; and they're just as frustrating for new contributors, which are a far more important audience to cater to than previous contributors (due to the much higher risk of attrition)

**Comment by ryanvanoss** [comment]
Doh, forgot about that after living in a non-GitHub world for quite some time...

Regardless, I still wouldn't kill the whole idea due to the inconvenience of formatting a message. Big picture there are a lot more wins here..

**Comment by ljharb** [comment]
The inconvenience is not formatting a commit message, it's figuring out how to correct a commit message for a commit you've already created and submitted.

As a collaborator on many projects, I find it's usually easier to manually correct commit messages upon merging (or directly on the branch, now that github allows that), and not to make it fail tests.

**Comment by ryanvanoss** [comment]
Manually correcting them is also an option, although it feels like a much bigger pain.

I think we're deviating from the core discussion though. To me the big question is around the focus of the project team -- do you prefer release automation, at the (IMO slight) cost of additional contribution guidelines, or do you want to keep the guidelines very loose to attract contributors?

**Comment by ljharb** [comment]
Other collaborators should of course weigh in; my preference is to *gently* encourage git hygiene (according to whatever rubric we all want), but not to hard-require it via automation, and to manually correct it on the PR when needed. "Managing releases" and "writing a changelog" imo are not the most pressing concerns of open source development, even if they seem seductively easy to automate.

**Comment by jessebeach** [comment]
> Other collaborators should of course weigh in; my preference is to gently encourage git hygiene (according to whatever rubric we all want), but not to hard-require it via automation, and to manually correct it on the PR when needed. "Managing releases" and "writing a changelog" imo are not the most pressing concerns of open source development, even if they seem seductively easy to automate.

I agree. I love structure that reduces thinking and friction overtime; structure with a constant coefficient of friction is less desirable. When pain exceeds that friction coefficient, structure makes sense. In our case, I think we're still small enough to calibrate organically.

Soft-closing for now. Feel free to re-open if you think there is more to discuss.
