### ISSUE TITLE
Update img-has-alt to reflect new suggestion about role='presentation'

### ISSUE THREAD

**Issue by camjc** [evcohen/eslint-plugin-jsx-a11y#162]
Looks like the docs don't reflect the new thinking about role='presentation' vs alt=''.
I'd change them myself but not 100% clear on what the new thinking is yet.

**Comment by evcohen** [comment]
thanks for reporting, good call. The discussion is in #102. I think we decided on preferring `alt=""` over `role="presentation"`. Basically, it will always error without `alt` property even if `role="presentation"` is there. If there is just `role="presentation"` it should error with a message to say to change to `alt=""`
