### ISSUE TITLE
New npm release with latest rules

### ISSUE THREAD

**Issue by christianvuerings** [evcohen/eslint-plugin-jsx-a11y#167]
Looks like we have a couple of awesome new rules sitting on `master`, would it be possible to do a release?

```
jsx-a11y/accessible-emoji
jsx-a11y/aria-activedescendant-has-tabindex
jsx-a11y/iframe-has-title
jsx-a11y/no-autofocus
jsx-a11y/no-distracting-elements
jsx-a11y/no-redundant-roles
```

**Comment by evcohen** [comment]
@christianvuerings yep waiting on a few outstanding PR's and then we'll cut a major release. thanks for listing the new rules for me, have to add to changelog 😛

**Comment by evcohen** [comment]
V4.0.0 published!
