### ISSUE TITLE
jsx-a11y/no-static-element-interactions shouldn't include label element

### ISSUE THREAD

**Issue by mzedeler** [evcohen/eslint-plugin-jsx-a11y#172]
The label element is interactive and thus shouldn't be included in the list of static elements addressed by this rule.

On MDN there is an example where the label accepts click events:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by ljharb** [comment]
Typically a click on a label shouldn't do anything except toggle/focus its linked input.

In other words, the label isn't interactive, the input it refers to is, and you should be responding to events on that input, not on the label.

**Comment by mzedeler** [comment]
First off, if the label actually responds to click events by placing focus somewhere, then by my definition, it is interactive. This should be enough to include `label` in the list of interactive elements.

But a whole other problem is that it seems that there is an issue with the way the events are propagated, because this:

    <div onClick="containerHandler">
      <input id="check" type="checkbox" onClick="checkboxHandler" />
      <label for="check">Check me</label>
    </div>

If `checkboxHandler` calls `stopPropagation`, the event doesn't bubble, even if you click the `label` element, but here:

    <div onClick="containerHandler">
      <input id="check" disabled type="checkbox" onClick="checkboxHandler" />
      <label for="check">Check me</label>
    </div>

If you click the label, the event will be sent to `containerHandler`.

**Comment by mzedeler** [comment]
Actually, I've spent some more time looking into this, and I'm closing this request.
Thanks for your time :-)
