### ISSUE TITLE
[v4.0.0] Definition for rule 'jsx-a11y/no-marquee' was not found

### ISSUE THREAD

**Issue by diegohaz** [evcohen/eslint-plugin-jsx-a11y#175]
Hi, do I need to change something to get rid of this error?

**Comment by evcohen** [comment]
Hi @diegohaz - yes this was removed in v4 in favor of no-distracting-elements rule

**Comment by logicoder** [comment]
Had same error, in my case the problem it's in this line from AirBnB eslint-config-airbnb rules:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js#L97

It also asks for old dependency.

**Comment by logicoder** [comment]
Added issue https://github.com/airbnb/javascript/issues/1290

**Comment by evcohen** [comment]
cool, thanks @logicoder  - if you install peerDependencies for eslint-config-airbnb with the command on their README i don't think you'll run into this issue (since they depend on older version)

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

**Comment by logicoder** [comment]
Sent PR: https://github.com/airbnb/javascript/issues/1290

Thanks @evcohen for the great work, I like your new rules so... I added `"jsx-a11y/no-marquee": 0` as a temporary workaround.
