### ISSUE TITLE
onclick-uses-role rule incorrectly reports violations non-DOM components

### ISSUE THREAD

**Issue by iancmyers** [evcohen/eslint-plugin-jsx-a11y#18]
By default I think the `onlick-uses-role` should only report violations on DOM elements, like `<div>`, `<span>`, etc. Instead, it reports violations on non-DOM JSXElements.

**Code**
`<TestComponent onClick={doFoo} />`

**Expected**
No violations.

**Actual**
jsx-a11y/onclick-uses-role: Visible, non-interactive elements with click handlers must have role attribute.

**Test Case**
`{ code: '<TestComponent onClick={doFoo} />', parserOptions },`

**Comment by evcohen** [comment]
Good call. Thinking that [HTML elements](https://facebook.github.io/react/docs/tags-and-attributes.html#html-elements) is a good reference point to all low-level DOM elements that JSX supports.

**Comment by evcohen** [comment]
Should be fixed in v0.6.1. Thanks for reporting 😃
