### ISSUE TITLE
accessible-emoji throwing error on non-emojis

### ISSUE THREAD

**Issue by aesopwolf** [evcohen/eslint-plugin-jsx-a11y#180]
I'm getting the following error for certain html entities. Particularly, the registered and copyright symbols: ® ©

```
Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby.
```

**Comment by aesopwolf** [comment]
Perhaps this list can be made an exception to this rule? http://emojipedia.org/unicode-1.1/

> Unicode 1.1 were pre-dated emoji inclusion in Unicode by 17 years, and included many characters primarily sourced from the Zapf Dingbats font.

> The following characters were added to Unicode in 1993 and given emoji presentation status in the years 2010-2015.

**Comment by evcohen** [comment]
what is preventing you from following the instructions in the error message to resolve?

**Comment by aesopwolf** [comment]
Sorry, I definitely can. It just seems a little weird to me... is the copyright symbol `©` really an emoji?

**Comment by evcohen** [comment]
cool - i'm not sure haha its in the unicode spec & its definitely an emoji on my iphone, but i see your point. Regardless, it can only help by adding the `span` with `role=img` and a label.

**Comment by aesopwolf** [comment]
Alright, no worries. Fair enough point. Thanks.

**Comment by evcohen** [comment]
@aesopwolf thanks for caring about a11y!!
