### ISSUE TITLE
How do I catch bubbling up of onKeyDown events

### ISSUE THREAD

**Issue by interactivellama** [evcohen/eslint-plugin-jsx-a11y#188]
I completely get that `onClick` should be on non-interactive elements. How should one catch bubbling up keyboard events though? Seems like `<div onKeyDown />` should be allowed for custom keyboard shortcuts. 

For instance, I have a datepicker calendar that is using `gridcell`'s but also allows going to the previous month by just pressing up from any of the days in the first week. One of our assistive tech users here at Salesforce has stated he loves the simplicity interaction over grid cell navigation with next/previous month.

Should I wrap everything in a form and catch them up at the top of the component or something like that? How do I catch bubbling up of `onKeyDown` events?

**Comment by interactivellama** [comment]
Another option maybe to just have a rule modifier that can keep `onClick` enabled to fail, but allow `onKeyDown` to pass.

**Comment by jessebeach** [comment]
Just give the element a role of `presentation` (which becomes `none` in the ARIA 1.1). We are dependent on the DOM to hang both our behavior layer and our presentation layer. I think it's perfectly fair to indicate that an element with behavior has no semantic mapping. There's no rule that our behavior tree must map to our presentation tree. The presentation tree must simply be perceptible, operable and understandable and we can achieve that flexibly.

**Comment by jessebeach** [comment]
Closing, fixed in master.
