### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [evcohen/eslint-plugin-jsx-a11y#203]
Package contains unnecessary directories and files - `src`, `.travis.yml` and others. I can do PR if your accept this issue.

**Comment by ljharb** [comment]
They are necessary; `npm explore foo && npm install && npm test` should always work.

.travis.yml I agree can be npmignored, though, if you think the handful of bytes is worth it.

**Comment by evilebottnawi** [comment]
@ljharb about `src` - https://github.com/thlorenz/convert-source-map/pull/56

**Comment by ljharb** [comment]
Certainly not everybody agrees that the above command  should always work,  but that does not change best practices.

**Comment by evilebottnawi** [comment]
@ljharb I'm concerned about this because we use docker and our images take up a lot of space, since most of it does not remove the extra unnecessary files from the packages :sob:

**Comment by ljharb** [comment]
The solution there is a postinstall script on your app to clean out the entire node_modules of files you know you don't need; not making PRs into each of the hundreds of deps you have installed.

**Comment by evilebottnawi** [comment]
@ljharb It's not always easy to find out which files are not specifically needed. Also, packages are updated frequently and new files are added, which makes tracking of this even more difficult. I think the best solution here is for the packets to keep track of what they publish themselves.

**Comment by evilebottnawi** [comment]
@ljharb For example, if you take popular repositories, they almost all publish the files only necessary for work, I think this is an indicator of good practice.

**Comment by ljharb** [comment]
Postinstall, remove from node_modules every .yml, .jsx, `__tests__` dir, and tests/test/spec dir that's next to a package.json - my guess is that shell command would save you way more space than a few PRs.

**Comment by evilebottnawi** [comment]
@ljharb some package use yml and jsx in root directory. It is really difficult.

**Comment by ljharb** [comment]
No package from npm should be using .jsx files; file issues on them if they are.

**Comment by evilebottnawi** [comment]
@ljharb also many packages have *.json files, which contain many unused information, but some use *.json as park of package, it is really difficult and шt will take even more time and in the future will spend more time than several PR

**Comment by ljharb** [comment]
I'm not suggesting deleting json files.

**Comment by evilebottnawi** [comment]
@ljharb i'm not really about completely removing them, I'm talking about that it would be nice to remove all unnecessary files, `json` is only example.

**Comment by ljharb** [comment]
Right but you only need to remove the significantly large ones.

**Comment by jessebeach** [comment]
+1 to removing src, scripts, __tests__, __mocks__ from the release package :)

closing because this is a bike shed we've already painted.
