### ISSUE TITLE
Best practices for modal overlay markup?

### ISSUE THREAD

**Issue by blord-fullscreen** [evcohen/eslint-plugin-jsx-a11y#223]
This sort of pattern is commonplace:

            <div className="modal-overlay" onClick={this.handleClose} />
            <div className="modal contents">
                Some information here.
              <button color={color} onClick={this.handleClose} />Close</button>
              <button color={color} onClick={this.handleOK} />OK</button>
            </div>

What is currently considered best practice for the overlay element? Making it an anchor or button element feels bizarre to me, though I'm willing to entertain the idea. Adding `role="button"` seems plausible (though because of #214 this currently doesn't pass the default airbnb config in eslint. Arrgh.) Thanks.

**Comment by ljharb** [comment]
an override comment seems appropriate

**Comment by blord-fullscreen** [comment]
You mean disabling linting for this one line? I have this general  pattern hundreds of times in the codebase I'm working on. And it's ubiquitous in the wild. Having to selectively disable linting for such a fundamental interface pattern makes me wonder if something needs to be rethought. I'd love to hear other ideas on the matter.

**Comment by ljharb** [comment]
@blord-fullscreen that a pattern appears frequently doesn't mean it's a good pattern nor "fundamental"; and code in the wild is irrelevant since one only lints one's own code.

If you're using an overlay hundreds of times in your codebase, why is that not using the fundamental pattern of code reuse, and shared as an `<Overlay>` component? Then it'd need a single override comment, not hundreds.

**Comment by blord-fullscreen** [comment]
> that a pattern appears frequently doesn't mean it's a good pattern nor "fundamental"

True. I didn't say modal windows were always good. I said that they are ubiquitous, and therefore authors of linters ought to think seriously about them.

> and code in the wild is irrelevant since one only lints one's own code.

Trivially true, but you're missing the point. You're producing a public product that provides widely used specific guidelines that help to shape the future of markup on the web.

> If you're using an overlay hundreds of times in your codebase, why is that not using the fundamental pattern of "code reuse", and shared as an <Overlay> component? Then it'd need a single override comment, not hundreds.

Great question. Answer: because the contexts are often very different, because it would be a significant refactor on a large existing codebase, and because there are more pressing features to be implemented. 

I'll just disable your product, the way you initially suggested, and advise other people to do the same.

Have a nice day.

**Comment by OscarBarrett** [comment]
For modal overlays I use `role="presentation"` , which is designed to hide it from screen readers and remove it from the accessible tree.
