### ISSUE TITLE
[v5.0.0] Definition for rule 'jsx-a11y/img-has-alt' was not found (jsx-a11y/img-has-alt)

### ISSUE THREAD

**Issue by YUzhva** [evcohen/eslint-plugin-jsx-a11y#227]
Hey hi.

I'm using `create-react-app` as quick starter-kit.

This error appears only with new `v5.0.0` at first line of my `.js` file where I'm importing react, like:
```javascript
import React from 'react';
```

![screenshot](https://lh3.googleusercontent.com/LP-1Pv_Fmt63rmptW2ex967C2dUnDnrTES8eY6vtgMVKCoDMfh9KTq8iTNmpLCwdvF9ei5xHExm1oX0=w2398-h1598-rw)

### How to reproduce
After creating new app `create-react-app my-app` I installed eslint `yarn add -D eslint` and configured it with eslint config script:
```bash
./node_modules/.bin/eslint --init
```

`.eslintrc.json`
```json
{
  "extends": "airbnb",
  "env": {
    "browser": true,
    "jest": true
  },
  "plugins": [
    "react",
    "jsx-a11y",
    "import"
  ],
  "rules": {
    "react/jsx-filename-extension": 0
  }
}
```

devDependencies:
```json
  "devDependencies": {
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.0.0",
    "eslint-plugin-react": "^7.0.0",
```

**Comment by ljharb** [comment]
The Airbnb config currently requires v4, not v5. Run `npm ls` and you'll see that your dependencies are invalid.
