### ISSUE TITLE
Difference configuration: recommended vs strict

### ISSUE THREAD

**Issue by Donaldini** [evcohen/eslint-plugin-jsx-a11y#234]
What is the difference between setting the config to strict or recommended?
I found this in the changelog of 5.0.0:

`[new] - Configs split into "recommended" and "strict".`

I couldn't find an issue about this or an updated readme.

**Comment by evcohen** [comment]
Hey @Donaldini thanks for raising this! we should better document the difference. Will keep this ticket open to track updating the docs, but for now you can find the difference [here](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/index.js#L40). Look for the `recommended` key and the `strict` key - mainly the difference is that `strict` just errors on everything 😄

**Comment by Donaldini** [comment]
@evcohen Would you like me to add this info to the readme or some other file in a more readable format?

**Comment by evcohen** [comment]
@Donaldini that would be amazing!!!

**Comment by Donaldini** [comment]
I created a PR for this https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/238

**Comment by ghostd** [comment]
How can we choose between the "strict" and the "recommended" version?

**Comment by Donaldini** [comment]
@ghostd
Under the Usage header you can find how to set the different modes, but I expanded the explanation a bit to account for the strict mode too. Added it to the PR #238 
Can never be too clear :)

**Comment by ghostd** [comment]
Thx, i missed that part of your PR

**Comment by evcohen** [comment]
Fixed in #238
