### ISSUE TITLE
Definition for rule 'jsx-a11y/img-has-alt' was not found error

### ISSUE THREAD

**Issue by valmassoi** [evcohen/eslint-plugin-jsx-a11y#235]
I get it at the top of my jsx files

I assume it is from (in v5 release notes):
[breaking] Refactor img-has-alt rule into alt-text rule

Do I need to add something to my .eslintrc to suppress the error?

I'm on versions:
  ```JSON
    "eslint": "3.19.0",
    "eslint-config-airbnb": "14.1.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "5.0.1",
    "eslint-plugin-react": "6.9.0",
```

**Comment by valmassoi** [comment]
closing because of #232

**Comment by hundsim** [comment]
For people coming here, the above mentioned #232 does still not provide any solution (April 20, 2018).

**Comment by ljharb** [comment]
@hundsim the solution is, run `npm ls` and ensure all your versions match (and ideally are on latest)
