### ISSUE TITLE
Consider removing yarn or greenkeeper

### ISSUE THREAD

**Issue by evcohen** [evcohen/eslint-plugin-jsx-a11y#248]
These two tools don't play nice together. When greenkeeper tries to upgrade a dependency, it doesn't update the yarn lock file, so there are constantly failing builds on those pull requests. yarn essentially renders greenkeeper useless other than reminders to upgrade the lock file manually.

**Comment by ljharb** [comment]
I vote removing yarn. Only apps should have lockfiles; by using it here, you're ensuring that this plugin's tests don't accurately replicate what users get when they run `npm install`.

**Comment by evcohen** [comment]
yay this should be resolved in #255 - removing all lock files and keeping greenkeeper

**Comment by evcohen** [comment]
jk #261
