### ISSUE TITLE
flow js error

### ISSUE THREAD

**Issue by wiscat** [evcohen/eslint-plugin-jsx-a11y#249]
Hi, after update package to 5.0.3 I have got this:
```
node_modules/eslint-plugin-jsx-a11y/src/rules/media-has-caption.js:54
 54:         if (child.type !== 'JSXElement') {
                       ^^^^ property `type`. Property not found in
 54:         if (child.type !== 'JSXElement') {
                 ^^^^^ Node
```

**Comment by gaearon** [comment]
This is because `eslint-plugin-jsx-a11y` ships the `src` as part of the npm package, and it includes Flow annotation. There is a past discussion about whether shipping `src` is necessary, which you can find at https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/156.

**Comment by Rulsky** [comment]
add eslint-plugin-jsx-a11y/src to flow's ignore in your .flowconfig solves problem
```
[ignore]
.*/node_modules/eslint-plugin-jsx-a11y/src/.*
```

**Comment by ljharb** [comment]
I believe this is both resolved in v6 (by temporarily removing `src` from npm), and also a flow bug.
