### ISSUE TITLE
Definition for rule 'jsx-a11y/alt-text' was not found error

### ISSUE THREAD

**Issue by alicerocheman** [evcohen/eslint-plugin-jsx-a11y#262]
Hi

I get this error at the top of my jsx files.
<img width="494" alt="capture d ecran 2017-06-09 a 13 59 26" src="https://user-images.githubusercontent.com/21168856/26974497-eb6b3428-4d1b-11e7-855d-bb2173ffab67.png">

Here are my dependencies:
```
"dependencies": {
    "axios": "^0.16.1",
    "leaflet": "^1.0.3",
    "material-ui": "^0.17.4",
    "prop-types": "^15.5.8",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-flexbox-grid": "^1.1.3",
    "react-helmet": "^5.0.3",
    "react-intl": "^2.1.5",
    "react-phone-number-input": "^0.11.5",
    "react-redux": "^5.0.4",
    "react-router": "^3.0.5",
    "react-router-redux": "^4.0.8",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-immutable-state-invariant": "^2.0.0",
    "redux-logger": "^3.0.1",
    "redux-multi": "^0.1.12",
    "redux-promise-middleware": "^4.2.0",
    "redux-thunk": "^2.2.0",
    "roboto-fontface": "^0.7.0"
  },
  "devDependencies": {
    "axios-mock-adapter": "^1.8.1",
    "babel-eslint": "^7.1.1",
    "eslint": "^3.16.1",
    "eslint-config-react-app": "^1.0.4",
    "eslint-plugin-flowtype": "^2.21.0",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.0.1",
    "intl": "^1.2.5",
    "node-sass": "^4.5.2",
    "npm-run-all": "^4.0.2",
    "react-scripts": "0.7.0"
  },
```

**Comment by evcohen** [comment]
Hi Alice! If you upgrade `react-scripts` to v1.0.7 it should work! The version you are using has a peerDependency of a lower version of `eslint-plugin-jsx-a11y` and uses older rules

**Comment by ljharb** [comment]
In general, `npm ls` will return nonzero here, and tell you what your dependency errors are. Whenever `npm ls` doesn't return zero, you should expect things to be broken :-)

**Comment by zerubeus** [comment]
@evcohen I have react-script 1.0.7 and still have the same problem `Definition for rule 'jsx-a11y/alt-text' was not found  jsx-a11y/alt-text` @Ijharb and `npm ls` return 0

**Comment by evcohen** [comment]
what is the output of `npm ls | grep "eslint"`

**Comment by robcaldecott** [comment]
Same issue here. `npm ls | grep "eslint"` gives this:

```bash
+-- eslint@3.19.0
| +-- babel-eslint@7.2.3
| +-- eslint-config-react-app@1.0.4
| +-- eslint-loader@1.7.1
| +-- eslint-plugin-flowtype@2.33.0
| +-- eslint-plugin-import@2.2.0
| | +-- eslint-import-resolver-node@0.2.3
| | +-- eslint-module-utils@2.0.0
| +-- eslint-plugin-jsx-a11y@5.0.3
| +-- eslint-plugin-react@7.0.1
```

**Comment by zerubeus** [comment]
@robcaldecott are you using create-react-app with react-script ?

**Comment by robcaldecott** [comment]
Yes. 1.0.7. npm4 and Node 7. If I remove the local ESLint dependency then the issue goes away so I can live with this.

**Comment by zerubeus** [comment]
@robcaldecott this is what I was about to recommend doing :)

**Comment by ljharb** [comment]
Note that all those deps aren't yet compatible with eslint 4.
