### ISSUE TITLE
Support eslint v4

### ISSUE THREAD

**Issue by evilebottnawi** [evcohen/eslint-plugin-jsx-a11y#266]

**Comment by evcohen** [comment]
Doesn't seem like anything needs to be done on our end, except upgrade peerDependencies. notice anything in the migration guide/changelog that would affect this plugin?

**Comment by ljharb** [comment]
@evcohen we should make sure that our peer dep is `^3 || ^4` tho, so it can be compatible with both.

Generally the changes are "invalid configs throw now", and some rules got stricter - so I don't think it would impact us.

**Comment by evilebottnawi** [comment]
@ljharb we can use `>=3` as in https://github.com/prettier/eslint-plugin-prettier/pull/30

**Comment by ljharb** [comment]
That's dangerous, because then a v5 breaking change might break us. Just like you should never do `*`, you shouldn't ever do `>`.
