### ISSUE TITLE
Release support eslint v4

### ISSUE THREAD

**Issue by steplov** [evcohen/eslint-plugin-jsx-a11y#269]
Hello,

Could you please bump the version and release the fix that you merged to master branch yesterday?

**Comment by evcohen** [comment]
@ljharb is this a minor or patch..?

**Comment by lencioni** [comment]
Looks like the next release should at least be minor, since it adds a new rule.

**Comment by ljharb** [comment]
Adding a new major to a peer dep is a minor anyways.

**Comment by evcohen** [comment]
was going to checkout at v5 and cherry pick. sounds good, both v5 and next release (v6 pending #257) will support eslint v4

**Comment by ljharb** [comment]
Awesome!

**Comment by ljharb** [comment]
Will v6 still support v3? (Hopefully)

**Comment by evcohen** [comment]
yep! but dropping v2 (#268)

**Comment by ljharb** [comment]
Great :-)

**Comment by evilebottnawi** [comment]
@evcohen friendly ping, can we release new version with support eslint v4?

**Comment by Arcanemagus** [comment]
Is this release waiting on anything? The discussion about things holding a release back seems to all be related to the v6 branch, as far as I can tell nothing is holding back a v5 release.

**Comment by p0wl** [comment]
Can we do anything to move this further? We are also waiting for this =)

thanks for your awesome project!

**Comment by evcohen** [comment]
[v5.1.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v5.1.0) released with eslint 4 support.

[v6.0.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v6.0.0) released as well!
