### ISSUE TITLE
Review: simplify and clarify rule names

### ISSUE THREAD

**Issue by evcohen** [evcohen/eslint-plugin-jsx-a11y#27]
Right now we have:

- [img-uses-alt](docs/rules/img-uses-alt.md): Enforce that img jsx elements use the alt attribute.
- [onclick-uses-role](docs/rules/onclick-uses-role.md): Enforce that non-interactive, visible elements (such as div) that have click handlers use the role attribute.
- [mouse-events-map-to-key-events](docs/rules/mouse-events-map-to-key-events.md): Enforce that onMouseOver/onMouseOut are accompanied by onFocus/onBlur for strictly keyboard users.
- [use-onblur-not-onchange](docs/rules/use-onblur-not-onchange.md): Enforce that onBlur is used instead of onChange.
- [no-access-key](docs/rules/no-access-key.md): Enforce that the accessKey prop is not used on any element to avoid complications with keyboard commands used by a screenreader.
- [label-uses-for](docs/rules/label-uses-for.md): Enforce that label elements have the htmlFor attribute
- [redundant-alt](docs/rules/redundant-alt.md): Enforce img alt attribute does not contain the word image, picture, or photo.
- [no-hash-href](docs/rules/no-hash-href.md): Enforce an anchor element's href prop value is not just #.
- [no-invalid-aria](docs/rules/no-invalid-aria.md): Enforce all aria-* properties are valid.
- [valid-aria-role](docs/rules/valid-aria-role.md): Enforce that elements with ARIA roles must use a valid, non-abstract ARIA role.
- [valid-aria-proptype](docs/rules/valid-aria-proptype.md): Enforce ARIA state and property values are valid.
- [role-requires-aria](docs/rules/role-requires-aria.md): Enforce that elements with ARIA roles must have all required attributes for that role.
- [no-unsupported-elements-use-aria](docs/rules/no-unsupported-elements-use-aria.md): Enforce that elements that do not support ARIA roles, states and properties do not have those attributes.
- [avoid-positive-tabindex](docs/rules/avoid-positive-tabindex.md): Enforce tabIndex value is not greater than zero.

Some of these names are verbose and unclear. Feel free to suggest more consistently clear and simple rule names based on descriptions.

Whatever results from this issue will be used for v1.0.0 release fairly soon.

**Comment by lencioni** [comment]
I think `avoid-positive-tabindex` could be `no-positive-tabindex` to be more consistent with other `no-*` rules.

**Comment by ljharb** [comment]
What if all image ones started with `img`, and all aria with `aria`, to start?

**Comment by lencioni** [comment]
`img-uses-alt` could maybe be `img-alt` or maybe `require-img-alt`.

`onclick-uses-role` might be better as `onclick-requires-role`?

**Comment by lencioni** [comment]
`valid-aria-role` could probably just be `valid-role`, or even `role`. Similarly `no-invalid-aria` could probably be rephrased in the positive `valid-aria`. And maybe `valid-aria-props` is more descriptive?

`role-requires-aria` feels a bit off. Maybe `required-aria-props-for-role`?

**Comment by lencioni** [comment]
Here's a full proposal for renaming. It takes @ljharb's idea of starting the name with a noun, where applicable, changes "uses" to "has" or "have", clarifies some things, and improves consistency. Thoughts?

- img-uses-alt -> img-has-alt
- redundant-alt -> img-redundant-alt
- onclick-uses-role -> onclick-has-role
- mouse-events-map-to-key-events -> mouse-events-have-key-events
- use-onblur-not-onchange -> no-onchange
- label-uses-for -> label-has-for
- no-access-key -> no-access-key
- no-hash-href -> href-no-hash
- no-invalid-aria -> aria-props
- valid-aria-role -> aria-role
- valid-aria-proptype -> aria-proptypes
- role-requires-aria -> aria-props-for-role
- no-unsupported-elements-use-aria -> unsupported-elements
- avoid-positive-tabindex -> tabindex-no-positive

**Comment by evcohen** [comment]
Thanks @lencioni and @ljharb 😄 Way better.

One change, I think though; we can maintain aria prefix for unsupported-elements: aria-unsupported-elements

Otherwise, looks really good.
