### ISSUE TITLE
Definition for rule 'jsx-a11y/href-no-hash' was not found (jsx-a11y/href-no-hash)

### ISSUE THREAD

**Issue by webMasterMrBin** [evcohen/eslint-plugin-jsx-a11y#294]
WHY HELP

**Comment by ljharb** [comment]
@webMasterMrBin we're going to need a bit more information. What version of the jsx-a11y plugin are you using? v6 removes this rule.

Are you using the airbnb config? The airbnb config requires v5 - is `npm ls` exiting zero?

**Comment by webMasterMrBin** [comment]
![image](https://user-images.githubusercontent.com/25171709/28198812-6230c482-6893-11e7-83c3-9fbacb2813ef.png)
version is wrong?

**Comment by ljharb** [comment]
Lots of things are wrong. The airbnb config also doesn't work with eslint v4 yet.

Use the install command in the eslint-config-airbnb readme, to get the proper versions of everything.

If `npm ls` doesn't exit successfully, nothing will work.

**Comment by webMasterMrBin** [comment]
ok thank you
