### ISSUE TITLE
explain motivation for `use-onblur-not-onchange`

### ISSUE THREAD

**Issue by ljharb** [evcohen/eslint-plugin-jsx-a11y#31]
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/use-onblur-not-onchange.md

It doesn't describe WHY the rule is important.

**Comment by evcohen** [comment]
The motivation behind this rule is mainly for `select` elements and their associated `options` - when using arrow keys to toggle between `options`, the `onChange` event will be triggered. `onBlur` is a more declarative type of user action - he/she _probably_ intended on changing focus. 

However, I can't think of another solid use-case for this rule...maybe we should scope it down to just select/option and rename. Thoughts?

**Comment by ljharb** [comment]
In general, I find it very weird that React fires "change" when the value isn't yet committed - ie, that React deviates from the entire internet in what "change" means. In addition, it won't be til v16 that "onChange" only fires when the value has *actually* changed.

That said, I don't have a strong opinion on it. Thanks for adding the motivation!
