### ISSUE TITLE
Bubbling from deep nested descendants

### ISSUE THREAD

**Issue by briziel** [evcohen/eslint-plugin-jsx-a11y#312]
Hi,
i've an issue with the following rule: "[eslint] Static HTML elements with event handlers require a role. (jsx-a11y/no-static-element-interactions)". My usecase is, that i have a footer with a bunch of links in it. I want to catch all click events at the footerwrapper so that i can spare to pass the onClick function as prop to all nested components. Accessability isn't affected because all links are semantic clickable. When i put a role="presentation" at the footer wrapper i will remove the hole semantic meaning from the footer and its content. Any helpful hints to avoid this? Just add an ignore statement for eslint?

regards
briziel

**Comment by ljharb** [comment]
Sounds like a special case, so an ignore statement makes sense to me.

**Comment by briziel** [comment]
Any need to warn in the docs? For example that you have to choose wisely to
add role="presentation"?

**Comment by ljharb** [comment]
If the docs encourage misusing the role attr, then yes, that sounds like a good improvement. (I'm mobile rn so I can't check easily)

**Comment by jessebeach** [comment]
> When i put a role="presentation" at the footer wrapper i will remove the hole semantic meaning from the footer and its content. Any helpful hints to avoid this? Just add an ignore statement for eslint?

Interesting case. My colleague @mcking65 is also encountering some issues with `role=presentation` that we're going to investigate. 

As @ljharb mentioned, an ignore statement is fine. I'll continue thinking about this case as well. Thank you for bringing it up!
