### ISSUE TITLE
Label is an interactive element

### ISSUE THREAD

**Issue by edds** [evcohen/eslint-plugin-jsx-a11y#321]
From the [list of interactive content elements](https://html.spec.whatwg.org/multipage/dom.html#interactive-content) in the HTML 5 spec. The `label` element is marked as an interactive element. However, as part of these lint rules it's marked as a non-interactive element.

Would you accept a PR to make the label correctly an element which accepts event listeners?

**Comment by ljharb** [comment]
What listeners are you hoping to add to a label?

**Comment by edds** [comment]
Personally I'd like a click handler, but there isn't any reason why you wouldn't want any events so you could, for example make a drag and drop interface.

**Comment by HugoGiraudel** [comment]
Seconded. We also add click handlers to labels every now and then.

**Comment by jessebeach** [comment]
> Would you accept a PR to make the label correctly an element which accepts event listeners?

@edds huh, I hadn't seen that bit in the HTML5 spec. I put up a PR to effect the change you suggested.
