### ISSUE TITLE
Error dependency `jsx-ast-utils` version 

### ISSUE THREAD

**Issue by markduan** [evcohen/eslint-plugin-jsx-a11y#327]
Hi, I saw the version of `jsx-ast-utils` in `package.json` dependencies section of `eslint-plugin-jsx-a11y 6.0.2`  is `2.0.0`, but the actually code I download is `1.4.0`.

I meet the same [issue](https://github.com/evcohen/jsx-ast-utils/issues/33) today, and this [PR](https://github.com/evcohen/jsx-ast-utils/pull/43) fixed it.

Could you please upgrade the version number and republish this repo? Thanks a lot!

**Comment by hammadzz** [comment]
@evcohen this would be nice as currently eslint is breaking because of this problem.

When did try branching off v5.1.1 to fix it (https://github.com/hammadzz/eslint-plugin-jsx-a11y/tree/fix-version-jsx-ast-utils) I ran into a new problem with eslint complaining: 
ESLint couldn't find the plugin "eslint-plugin-jsx-a11y"

**Comment by Waize** [comment]
same here @markduan 
please fix this

**Comment by cheton** [comment]
Hi @evcohen 

The published version of `eslint-plugin-jsx-a11y@6.0.2` on NPM is still using `eslint-plugin-jsx-a11y@^1.4.0`
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/v6.0.2/package.json#L66
```
"jsx-ast-utils": "^1.4.0"
```

Will be a new version of `eslint-plugin-jsx-a11y` published to NPM to reflect the latest changes of the master branch?

**Comment by ibiBgOR** [comment]
![tweet](https://user-images.githubusercontent.com/6171670/33116353-b9ef6506-cf64-11e7-8447-b5be809abdb5.png)
I tweeted him yesterday.

**Comment by evcohen** [comment]
published [v6.0.3](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v6.0.3)
