### ISSUE TITLE
jsx-a11y/anchor-is-valid

### ISSUE THREAD

**Issue by inferusvv** [evcohen/eslint-plugin-jsx-a11y#340]
I have a `Link` component:

```
class Link extends React.Component {
  render() {
    const { to, children, ...props } = this.props;
    return (
      <a href={to} {...props} onClick={this.handleClick}>
        {children}
      </a>
    );
  }
}
```

And use it like this:

`<Link to="/somewhere">Link</Link>`

But I am getting ESLint error `The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid`

P.S. This `Link` components is a part of react-starter-kit by kriasoft

**Comment by ljharb** [comment]
You'll have to provide settings that denote `to` as a "specialLink" property; see the rule docs.

**Comment by skube** [comment]
FYI, here's a [link to the rules docs](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details)

**Comment by bstaruk** [comment]
This worked for me (`.eslintrc`):

```json
{
  "rules": {
    "jsx-a11y/anchor-is-valid": [ "error", {
      "components": [ "Link" ],
      "specialLink": [ "to" ]
    }]
  }
}
```

**Comment by bstaruk** [comment]
This worked for me:

`.eslintrc`

```json
{
  "rules": {
    "jsx-a11y/anchor-is-valid": [ "error", {
      "components": [ "Link" ],
      "specialLink": [ "to" ]
    }]
  }
}
```

Sorry to necro a closed issue, but this came up when searching around to debug a similar issue I had. This was the solution I came up with, figured I'd share it for future debuggers.

**Comment by gknapp** [comment]
It seems like "to" should be `specialLink` by default here.

**Comment by ljharb** [comment]
If it’s an a, it should always have an href as a noJS fallback.

**Comment by ljharb** [comment]
Or put another way - if it doesn’t have a url, it’s not semantically a link.
