### ISSUE TITLE
<Link> require anchor-is-valid

### ISSUE THREAD

**Issue by MinhQuangPham** [evcohen/eslint-plugin-jsx-a11y#341]
I recently updated eslint, and reinstalled all the lastest update of packages which following by **Airbnb** style. After updated, I got new error: Link component required **a valid anchor.** 
The error will be disappeared if I add `href` props, but as you know, Link component always only go with `to` props. I already checked peer dependencies by `npm ls` and it shows nothing incompatible here.
Here's my package.json: 
```
    "eslint": "^4.8.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0"
```
If I roll back `"eslint-config-airbnb": "^15.1.0"` and `"eslint-plugin-jsx-a11y": "^5.1.1"`, then everything work back, no error show. 
Don't both of new version of eslint-plugin-js-a11y and eslint-config-airbnb incompatible?

**Comment by ljharb** [comment]
When `npm ls` exits nonzero, you can't expect anything to work.

The "valid anchor" error is correct; for react-router's Link, you'll need to configure the eslint-plugin-import rule to set the "specialLink" property to include "to", so it knows you've provide a valid href to the link.

**Comment by MinhQuangPham** [comment]
Hi Jordan,
Thanks for fast replying!
Probably your solution will handle my problem, but I just curious
something.
Here's my package.json before update:
"eslint": "^4.7.1",
"eslint-config-airbnb": "^15.1.0",
"eslint-plugin-import": "^2.7.0",
"eslint-plugin-jsx-a11y": "^5.1.1",
"eslint-plugin-react": "^7.3.0",
And after updated:
"eslint": "^4.8.0",
"eslint-config-airbnb": "^16.0.0",
"eslint-plugin-import": "^2.7.0",
"eslint-plugin-jsx-a11y": "^6.0.2",
"eslint-plugin-react": "^7.4.0",
Before update, I have no error. After updated, error appeared as I
mentioned. The error only disappear after I reinstalled
eslint-config-airbnb@15.1.0 and eslint-plugin-jsx-a11y@5.1.1.
As you can see, eslint-plugin-import before and after update have nothing
change. So I just guessed the issue come from eslint-config-airbnb and
eslint-plugin-jsx-a11y.

**Comment by ljharb** [comment]
The issue is that eslint-config-airbnb enabled a new eslint-plugin-jsx-a11y rule; that rule by default *correctly* reports an error on all react-router `Link` usages.

eslint-config-airbnb does not have any special react-router configuration; as such, you will have to (along with the v16 eslint-config-airbnb upgrade) manually configure the `anchor-is-valid` rule with `specialLink: ['to']` (see the rule docs for details).

**Comment by MinhQuangPham** [comment]
Ok, I got it. Thank you so much!

**Comment by Y-Taras** [comment]
Could anyone give an example with manually configure the `anchor-is-valid` rule?

**Comment by MinhQuangPham** [comment]
Here's what you need, simple just add new rule which you want in `rules` object in `.eslintrc.js` file.
```
module.exports = {
  "env": {
    "browser": true
  },
  "extends": "airbnb",
  "parser": "babel-eslint",
  "globals": {
    "require": true
  },
  "rules": {
    "jsx-a11y/anchor-is-valid": [ "error", {
      "components": [ "Link" ],
      "specialLink": [ "hrefLeft", "hrefRight", "to" ],
      "aspects": [ "noHref", "invalidHref", "preferButton" ]
    }]
  }
};
```
