### ISSUE TITLE
is aria-current not a valid attribute?

### ISSUE THREAD

**Issue by Michaeljdu2010** [evcohen/eslint-plugin-jsx-a11y#353]
Hi, thanks for this library.  It's been very useful!  However, ran into a bit of a problem using it lately. I'm trying to add an aria-current='page' on a li tag to symbolize the current page, yet the linter keeps telling me:

error  aria-current: This attribute is an invalid ARIA attribute   

I'm pretty sure aria-current is a valid ARIA attribute.  Was it not implemented in the library?  Or am I mistaken in using it on a LI tags to symbolize  the current page?  Thanks for your help!

**Comment by ljharb** [comment]
I believe `aria-current` is [proposed](https://www.w3.org/TR/wai-aria-1.1/#aria-current) for ARIA 1.1; and says that "page" is indeed a valid value for it.

This plugin uses https://www.npmjs.com/package/aria-query which [seems](https://github.com/A11yance/aria-query/blob/95edfa3a6a848c60a45ffa1f09424b72a343a335/src/etc/roles/abstract/roletypeRole.js#L16) to be valid on [list items](https://github.com/A11yance/aria-query/blob/03277ee774ac2d6bcdfc916be72a2358aabe800a/src/etc/roles/literal/listitemRole.js#L40).

I think @jessebeach is our resident expert here.

**Comment by jessebeach** [comment]
I'll look into it. 

@Michaeljdu2010 ideally you'd put this attribute on the link/button rather than on a list item. The link/button should be inside the list item. Don't turn li's into links or buttons; then they lose their listiness.

**Comment by Michaeljdu2010** [comment]
Ah, thanks Jesse.  I just moved the attribute from the li to the button inside.  It seems to work better that way.  (the aria-current attribute still hits the same error though)

**Comment by jessebeach** [comment]
Ok, good to know. That's definitely an error in the tool. Add a suppression
comment for now. I'll get around to a fix this week.

**Comment by jessebeach** [comment]
You're also welcome to propose a PR :) It's probably an easy fix; just a
missing entry either in aria-query or axobject-query or
eslint-plugin-jsx-a11y.

**Comment by jessebeach** [comment]
@Michaeljdu2010 sorry for the long delay in responding to this issue. The error you received comes from the `aria-props` rule. `aria-current` is present in the passing cases as of version 6:

<img width="405" alt="1__jessebeach_macbook-pro-2____code_evcohen_eslint-plugin-jsx-a11y__zsh_" src="https://user-images.githubusercontent.com/345913/33002339-65d6863c-cd68-11e7-89a9-e60782543d51.png">

The violation should resolve when you upgrade.

**Comment by Michaeljdu2010** [comment]
@jessebeach  Ah I see, I will update our version of a11y.  Thanks for looking into this Jesse, appreciate it.
