### ISSUE TITLE
Plugin finds error despite htmlFor defined

### ISSUE THREAD

**Issue by wojtekmaj** [evcohen/eslint-plugin-jsx-a11y#354]
Hi,
I have the following piece of code in my React component:

```jsx
        <div>
          <input
            id="renderTextLayer"
            type="checkbox"
            checked={renderTextLayer}
            onChange={this.onRenderTextLayersChange}
          />
          <label htmlFor="renderTextLayer">Render text layers</label>
        </div>
```

and it shows me this error:

![obraz](https://user-images.githubusercontent.com/5426427/32694159-f610791e-c738-11e7-842a-19db4ad6d25b.png)

I don't think I have done something wrong. I'm using the newest version of eslint and the newest version of this plugin (via airbnb config).

**Comment by ljharb** [comment]
Nope - the input needs to be *inside* the label *as well* as being for/id-linked, for full a11y coverage.

**Comment by wojtekmaj** [comment]
Ah, alright. Thank you!

**Comment by andrewcroce** [comment]
@ljharb I'm curious what the reference is for requiring the input be _inside_ the label. The A11y Project checklist only recommends the association of a label with `for` attribute. http://a11yproject.com/checklist.html#forms

**Comment by andrewcroce** [comment]
@ljharb Thank you. With all due respect, however, that doesn't answer my question. The A11y project checklist gives the following example [here](https://a11yproject.com/checklist.html#forms):

```
Associated label for all form controls (e.g. input, select etc.) 
(e.g. <label for="name">Name:</label><input id="name" type="text">)
```

Notice the label is a sibling of the input.

What is the source you are using for establishing this additional lint requirement that inputs be a child of the label?

**Comment by ljharb** [comment]
I'm saying that the A11y project's example is insufficient, or potentially incorrect.

The source is "there exists software that requires it" - the spec is irrelevant to accessibility, what's relevant is what devices/browsers/engines do.
