### ISSUE TITLE
Adding role="list" to a <ul> or <ol> triggers warning by default

### ISSUE THREAD

**Issue by rikschennink** [evcohen/eslint-plugin-jsx-a11y#392]
Fantastic that there's accessibility linting for jsx but I noticed it throwing a warning when adding `role="list"` to a `<ul>` or `<ol>`. 

However, when the style `list-style:none` is set, VoiceOver stops treating the list as a list. It then needs the `role="list"` attribute to still read out the total list items and index of the current item. 

So, maybe no default warning for role lists, or check if the `list-style` is set to `none` and then throw a warning (I imagine that might be tricky)?

**Comment by jessebeach** [comment]
@rikschennink, @blackflame007 added a test case for your issue. It currently passes. Please reopen this issue with a failing test case if you are still experiencing this problem.

#570
