### ISSUE TITLE
Is it necessary enable click-events-have-key-events rule when develop in a mobile device?

### ISSUE THREAD

**Issue by mrdulin** [evcohen/eslint-plugin-jsx-a11y#394]
I think it's not necessary enable `click-events-have-key-events` rule when develop in a mobile device. 

Am I correct?

**Comment by ljharb** [comment]
Mobile devices have touch events, which do trigger click events often. It’s still necessary.

**Comment by mrdulin** [comment]
@ljharb I mean the key events, not click event.

**Comment by ljharb** [comment]
Mobile devices have keyboards, and "next field" and "previous field" logic as well. You can also hook a full keyboard up to any mobile device.

**Comment by mrdulin** [comment]
@ljharb I know, thanks. I forget mobile device can connect a keyboard, like blue tooth keyboard.
