### ISSUE TITLE
Definition for rule 'jsx-a11y/href-no-hash' was not found

### ISSUE THREAD

**Issue by chiaweilee** [evcohen/eslint-plugin-jsx-a11y#396]
> ./src/index.js
  Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash

> ./src/service/registerServiceWorker.js
  Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash

> ./src/components/App.js
  Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash

```{
"eslint": "^4.16.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-standard": "^11.0.0-beta.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-react": "^7.4.0",
    "eslint-plugin-redux-saga": "^0.6.0",
    "eslint-plugin-standard": "^3.0.1",
}

// http://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
    "node": true,
    "jest": true
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: 'airbnb',
  // required to lint react files
  plugins: [
    'import',
    'react',
    'jsx-a11y'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}
```

Please help me.

**Comment by ljharb** [comment]
Do any of those files have any inline eslint comments? Are there any other eslintrc files?

**Comment by chiaweilee** [comment]
@ljharb I removed .babelrc.

**Comment by ljharb** [comment]
I wouldn’t expect that to be related.

What does `npm ls` say? If that doesn’t exit successfully, nothing can be expected to work.

**Comment by pincheira** [comment]
For those of you not yet able to make it work, I added this on my `.eslintrc` https://github.com/mmazzarolo/eslint-plugin-react-app/blob/master/README.md#known-issues 

Cheers 🤙🏻

**Comment by wuxyman** [comment]
Such as;if you use eslint-config-react-app(v5.2.x); you should use     npm view eslint-config-react-app peerDenpendencies      to install right version.Do not write rule jsx-a11y/href-no-hash in any files, then you have no error.I have successed.
