### ISSUE TITLE
Every file errors with `'jsx-a11y/href-no-hash' was not found`

### ISSUE THREAD

**Issue by jasonrhodes** [evcohen/eslint-plugin-jsx-a11y#397]
May be related to #396 but not sure. Greenkeeper just updated a bunch of our dependencies in this PR: https://github.com/SparkPost/2web2ui/pull/264/files, and this plugin went from 5.1.1 to 6.0.3 ... as far as I can tell we don't even use this plugin, it's there because we ejected from CRA a while back and it came "for free".

However, in this PR we have 615 errors because what seems like every single file in our repo errors with this:
```
  1:1  warning  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
```

The package-lock file only shows one instance of this plugin installed:
```
$ cat package-lock.json | grep jsx-a11y
    "eslint-plugin-jsx-a11y": {
      "resolved": "https://registry.npmjs.org/eslint-plugin-jsx-a11y/-/eslint-plugin-jsx-a11y-6.0.3.tgz",
```

My plan is to just remove this plugin from our repo so we can move on, but I wanted to log this here in case it was helpful to anyone else in a similar situation.

**Comment by jasonrhodes** [comment]
Update: downgrading this back to 5.1.1 also solved the problem. Still not totally sure why.

**Comment by ljharb** [comment]
Because the rule in question was removed in v6. Do you have any reference to that rule in your eslint config? If you ejected from CRA, you may.

**Comment by jasonrhodes** [comment]
Anyone who is using CRA and also keeps their deps up to date (via something like Greenkeeper) is gonna hit this, because CRA current references the rule. 

More here: https://github.com/facebook/create-react-app/issues/3418#issuecomment-362839726

**Comment by ljharb** [comment]
Sounds like the incompatibility is that the CRA eslint config doesn’t support v6 of this plugin.

**Comment by jasonrhodes** [comment]
Correct, and peer dependencies are pain and suffering. :)

**Comment by ljharb** [comment]
Peer deps work fine; but tools like greenkeeper sadly don’t yet handle them properly. I’d suggest adding an `npm ls` to your tests, which will make greenkeeper’s builds fail when peer dep are invalid.

**Comment by crobinson42** [comment]
### Work-around

If you're like me and you found this post because you're experiencing  `"jsx-a11y/href-no-hash" was not found` due to `eslint-config-airbnb` or some other eslint config and you want to update to the latest versions of those eslint configs, you can circumvent the error at the top by placing this in your CRA's `.eslintrc` file:

```
{
  "extends": [
    "react-app",
    "airbnb"
  ],
  "rules": {
    "jsx-a11y/href-no-hash": [0], 
  }
}
```

**Comment by iFlameing** [comment]
__work Around__

You have to just make some change in .eslintrc file
{
    "rules": {
      "jsx-a11y/href-no-hash": [0]
    }
  }
and save if you are using the create react app to build your app and facing this problem.
