### ISSUE TITLE
jsx-a11y/no-redundant-roles options not working

### ISSUE THREAD

**Issue by christreanor** [evcohen/eslint-plugin-jsx-a11y#410]
I'm getting errors coming through with the navigation element having a role of navigation, even though I'm including it in the options. I've also tested with other elements and it seems the options just get ignored... or I'm not understanding something.

`"jsx-a11y/no-redundant-roles": [ "error", {
    "nav": ["navigation"],
    "button": [ "button" ]
}],`

**Comment by ljharb** [comment]
The rule isn’t yet published; you can tell by looking to see what version tags are listed on the [commit](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/rules/no-redundant-roles.js) that adds it.

**Comment by christreanor** [comment]
My apologies, it seemed like it was put into the latest release (6.0.3) and I don't know how to do the above ;)

Thank you for getting back to me so quickly. Any idea when the rule will be published?
