### ISSUE TITLE
Redundant label-has-for default?

### ISSUE THREAD

**Issue by hjylewis** [evcohen/eslint-plugin-jsx-a11y#418]
Is there a reason why [`label-has-for`](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md)'s `required` option defaults to `"every"`?

It seems redundant to require both nesting *and* the `htmlFor ` attribute. I was confused why the linting was failing despite whether I nested or used `htmlFor `.

**Comment by ljharb** [comment]
It's not redundant; some accessibility devices *only* support nesting; others *only* support for-ID linking - the only way to cover 100% of devices (an important goal of accessibility is that *everyone* has access) is to do both.

**Comment by afercia** [comment]
Some references:

Old WCAG 2.0:
**H44: Using label elements to associate text labels with form controls**
https://www.w3.org/TR/WCAG20-TECHS/H44
(doesn't mention nesting at all)

A previous version discouraged implicit labelling (nesting)
https://www.w3.org/TR/2008/WD-WCAG20-TECHS-20080430/H44.html
> The HTML and XHTML specifications allow both implicit and explicit labels. However, some assistive technologies do not correctly handle implicit labels



**Labeling Controls**
https://www.w3.org/WAI/tutorials/forms/labels/

> A label and a form control should be associated with each other **either implicitly or explicitly**

> Whenever possible, use the label element to associate text with form elements **explicitly**

> Generally, explicit labels are better supported by assistive technology.


A very important post by Steve Faulkner, Paciello Group a11y specialist and HTML 5.1 co-editor among many other things. The post is a bit old (2011) but still valid.

**HTML5 Accessibility Chops: form control labeling**
https://developer.paciellogroup.com/blog/2011/07/html5-accessibility-chops-form-control-labeling/
> Until browser implementers fix their accessibility support, if you want controls to be understandable to AT users label controls using for and id. Do not use the control inside the label method. **Do not use a combination of the 2 methods.**


**Labeled With Love**
by Aaron Gustafson
https://www.aaron-gustafson.com/notebook/labeled-with-love/
> Dragon’s Naturally Speaking also doesn’t recognize implicit association

Overall, I'd tend to think this issue should be re-opened for better investigation and research.
/Cc @ljharb @aardrian @stevefaulkner

**Comment by ljharb** [comment]
Can you provide an example of something that breaks why both? Using both nesting and linking has been a best practice for over a decade, and I’ve never once heard a report that using both is harmful besides that one article you linked, which i claim is wrong.

**Comment by afercia** [comment]
@ljharb well it's not only the article... (maybe better to check who wrote it before claiming it's wrong? 🙂 ). Have you checked the W3C tutorial? https://www.w3.org/WAI/tutorials/forms/labels/
There, it's clearly stated "either implicitly or explicitly".

As far as I can remember, using both caused the label to be announced twice in some old browsers / AT combinations. However, I'm not arguing or blaming anyone 🙂 I'm only asking to reopen this issue for better research and investigation. I'm pretty sure @aardrian and @stevefaulkner can answer your question better than me and provide data if necessary.

**Comment by ljharb** [comment]
If someone can provide a concrete browser or device - ideally still in use - where using both is problematic, I’ll be happy to reopen.

**Comment by afercia** [comment]
There is a table with support data linked in the Steve Faulkner post. Data are from 2012. See http://www.html5accessibility.com/tests/form-labels.html

From there, you can see that all software tested read out correctly the label:
- with only label using for/id (except VoiceOver with Opera 11.6 which is a dead browser)
- with only label wrapped

So, asking by default to implement both is a bit pointless. As per potential problems caused by using both, I'd defer to someone more expert and updated than me.
