### ISSUE TITLE
heading-has-content doesn't work for custom components

### ISSUE THREAD

**Issue by pdhoopr** [evcohen/eslint-plugin-jsx-a11y#429]
Hi there,

Just ran into this issue on v6.0.3. I have a custom heading component and added it to my config like this:

```js
'jsx-a11y/heading-has-content': ['error', { components: ['Title'] }]
```

I'd expect a linting error when trying to use it without content (`<Title />`), but none is given. Still works for the standard h1-h6 elements.

Comparing the code to the `anchor-has-content` rule, it seems the actual `components` array from the options is not what's being appended to the array of headings to check (at [this line of code](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/rules/heading-has-content.js#L38)), but rather its parent object. Tweaking it locally to match the pattern in `anchor-has-content` seems to fix it for me:

```js
const options = context.options[0] || {};
const componentOptions = options.components || [];
const typeCheck = headings.concat(componentOptions);
```

**Comment by ljharb** [comment]
Thanks, this is a great catch. Want to submit a PR for it?

**Comment by pdhoopr** [comment]
Sure, happy to. I'll try to have one ready soon.

**Comment by zackify** [comment]
I'm on CRA 2.0 and this issue is killing me lol. So many lint errors, thank you for submitting a fix
