### ISSUE TITLE
update no-noninteractive-element-to-interactive-role rule to support role='tablist' on <ul>'s

### ISSUE THREAD

**Issue by jbadan** [evcohen/eslint-plugin-jsx-a11y#436]
Hello everyone!

Thanks for creating an awesome set of guidelines to help improve accessibility!

I do have one piece of feedback that I think might lead to a better change for the rule `no-noninteractive-element-to-interactive-role `. It appears that this rule fails when you add `role='tablist'` to a `<ul>`. While `<ul>` is non interactive, `tablist` is also non-interactive and its only the tabs inside the tablist which receive action. This can cause problems in interfaces where graceful fallback is preferred and the author intended to use a `<ul>` as a tablist instead of a generic div in the case that the users assistive technology does not support HTML5 roles.

**Comment by ljharb** [comment]
@jbadan why close this?

**Comment by jbadan** [comment]
@ljharb Hi 👋 I had missed the section of the docs that shows how to allow this behavior. See: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-to-interactive-role.md#rule-details
