### ISSUE TITLE
anchor-has-content issue

### ISSUE THREAD

**Issue by mbavio** [evcohen/eslint-plugin-jsx-a11y#443]
Something as simple as `<a>This is a piece of text</a>` is giving me the `Anchors must have content and the content must be accessible by a screen reader.` error. It works if the children is a node rather than text.

Currently using `eslint@5.0.0-rc.0` and the latest version of this plugin.

**Comment by ljharb** [comment]
Since eslint 5 is not yet released, it's highly likely that any plugin might not work with it yet.

When it's released, we'll address it. Thanks for the report!

**Comment by openjck** [comment]
I'm seeing this on eslint v4 as well. I think this is related to #440.

**Comment by ljharb** [comment]
@openjck thanks; in that case, this is a dupe of that :-)
