### ISSUE TITLE
href="mailto:info@example.com" anchor tag shows anchor-is-valid warning

### ISSUE THREAD

**Issue by DamianPereira** [evcohen/eslint-plugin-jsx-a11y#444]
I have created a new app with create-react-app@2.0.0-next.66cc7a90. I don't have a .eslintrc file, so I'm guessing everything comes default from CRA.

I have the following link:

`<a href="mailto:info@example.com">info@example.com</a>`

As far as I know this is a correct use case for the anchor tag and should display a warning. Is there something I'm missing should I use a button tag?

**Comment by ljharb** [comment]
This looks correct to me; can you share the exact warning you’re getting?

**Comment by DamianPereira** [comment]
Just tried to reproduce on a new project, and could not, must have been an error in another place. Sorry for the noise!
