### ISSUE TITLE
Image with expanded props throws `The prop must be a JSXAttribute collected by the AST parser.`

### ISSUE THREAD

**Issue by tricoder42** [evcohen/eslint-plugin-jsx-a11y#459]
Hi,
I have this wrapper around an image:

```jsx
export default class MaybeImage extends React.Component {
  state = {
    error: false,
  }

  handleError = e => this.setState({ error: true })

  render() {
    const { alt, src, ...props } = this.props
    return !src || this.state.error ? (
      <span {...props}>{alt}</span>
    ) : (
      <img src={src} alt={alt} onError={this.handleError} {...props} />
    )
  }
}
```

But it breaks eslint with an error: **The prop must be a JSXAttribute collected by the AST parser.** It's not just an eslint error, rather unhandled javascript exception. I think #7 might be related, but even when I disable the rule, it still breaks.

[This line](https://github.com/evcohen/jsx-ast-utils/blob/master/src/propName.js#L5) in `jsx-ast-utils` gets the prop name, but it doesn't count with spread operator. This is the content of `prop` which throws an error:

```js
   Node {
     type: 'JSXSpreadAttribute',
     argument:
      Node {
        type: 'Identifier',
        name: 'props',
        _babelType: 'Identifier',
     },
     _babelType: 'JSXSpreadAttribute',
     parent:
      Node {
        type: 'JSXOpeningElement',
        attributes: [Array],
        name: [Node],
        selfClosing: true,
        _babelType: 'JSXOpeningElement',
      } }
```

What's your suggestion here? Pass props explicitely so it can be statically analyzed? Or is it bug in `jsx-ast-utils`? I think it should show an eslint error or warning at best, but not throw an exception.

Cheers 👋

**Comment by ljharb** [comment]
This definitely seems like a bug between jsx-ast-utils and this plugin.

**Comment by tricoder42** [comment]
Indeed, but I can't track down since when it's happening. The condition is there for 2 years and I've been using spread operator without any problems. It started failing after recent upgrade.

**Comment by ljharb** [comment]
That strongly suggests it's an issue with this plugin.

**Comment by jessebeach** [comment]
Ok, looking into it.

**Comment by jessebeach** [comment]
@tricoder42 what rule exactly is failing on this JS error? `img-uses-alt` doesn't exist any more. And a rule like `alt-text` has a case `{ code: '<img {...this.props} alt="foo" />' }`, which passes just fine.

I don't doubt the incorrect behavior that you're running into. I just need some help to track down exactly what's failing.

**Comment by jessebeach** [comment]
@tricoder42 if you could post a PR with an updated, failing test case, that would be very helpful.

**Comment by tricoder42** [comment]
I'm not sure either, I'm using `plugin:jsx-a11y/recommended` config which has a lot of rules enabled. When the eslint fails with exception, I don't see the rule name which caused it.

**Comment by tricoder42** [comment]
I tried to create test case but it seems I can test only for single rule, not all of them... let's see what I can do.

This is my config, when I strip down all other plugins/configs:

```js
module.exports = {
  parser: 'babel-eslint',

  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      generators: true,
      experimentalObjectRestSpread: true,
    },
  },
  extends: ['plugin:jsx-a11y/recommended'],
  plugins: ['jsx-a11y']
}
```

**Comment by jessebeach** [comment]
@tricoder42 you can add `console.trace();` just before the exception in thrown in `jst-ast-utils`; just edit the file in `node_modules` directly. That should dump the execution stack trace to the console just before eslint errors out.

**Comment by tricoder42** [comment]
@jessebeach Nice! Thank you. Here's the PR #460 with test case and possible fix.
