### ISSUE TITLE
isInteractiveElement() test for higher level JSX components produces false negatives when components are similarly named to DOM elements

### ISSUE THREAD

**Issue by SohKai** [evcohen/eslint-plugin-jsx-a11y#46]
The [test to skip testing higher level JSX components](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/util/isInteractiveElement.js#L37) in isInteractiveElement seems to be too broad as it uses `.toUpperCase()` on the `tagName` before comparing with the map of DOM elements. This produces false negatives when a custom component is named similarly to a DOM element, but with capitalizations (eg. `Button` vs. `button`).

To my knowledge, removing the `.toUpperCase()` should fix this, but I'm not sure if there are non-React use cases of JSX where, for example, `Button` might mean the same as `button`, or if there were any other factors that required relaxing the case-sensitivity.

**Comment by evcohen** [comment]
yeah, i think the goal is to use [String.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) but I'm unsure of the support on node and how it transpiles through babel. Let me make a commit using `String.normalize` on a separate branch and see how the build works out over different versions of node to see if that's a better approach than uppercasing. 

In the meantime, I'd give a more descriptive name to your wrapper component or just use `<button />` inline in your higher-order components.

**Comment by ljharb** [comment]
This will hit Airbnb too, as we have a `Button` component - and the difference between `Button` and `button` is important. I'm not sure why `String.normalize` would fix it, but I'd expect prefixing all DOM elements with "dom:" or something might be useful?

**Comment by evcohen** [comment]
Yeah, after re-thinking it I agree. About to put in a fix by lower casing all of the dom elements in the JSON file because we can safely assume that low-level DOM elements are all lower-cased.

**Comment by evcohen** [comment]
[v1.2.1](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/1.2.1) published 

Thanks for reporting @SohKai - subtle but important bug to find! 😄
