### ISSUE TITLE
Allow <div> for accessible-emoji

### ISSUE THREAD

**Issue by hejmartin** [evcohen/eslint-plugin-jsx-a11y#478]
Hi!

As the reasoning behind the requirement for `<span>` in the accessible-emoji rule, [according to the linked article](https://tink.uk/accessible-emoji/), is that it is semantically neutral, I think the rule should allow the use of `<div>` as a wrapping element as well. It makes more sense to use a div rather than a span in certain places, i.e. inline vs. block elements.

(Also, thanks for a great plugin! 👍 )

**Comment by ljharb** [comment]
Since emoji is an inline text character, when would you want to use it in a block context without any other text?

**Comment by hejmartin** [comment]
This is my current use case:
![image](https://user-images.githubusercontent.com/1826675/44633245-b3ae6f80-a988-11e8-82ca-f89fb1d99953.png)

I guess that I could split this into one element (div, p) for the block formatting and add an extra span for just the emoji… but I still think that enforcing it to specifically be a span, when a div is equally semantically neutral, is a bit unnecessary.

**Comment by evcohen** [comment]
Thanks for filing this and for the kind words! I don't think this is a necessary change to make to the plugin. If you'd like to keep your current DOM structure, you can just ignore the warning or add the `span`. Feel free to re-open if you feel strongly and we can continue discussion 😄
