### ISSUE TITLE
dialog role, keyboard events and jsx-a11y/no-noninteractive-element-interactions

### ISSUE THREAD

**Issue by danhaggard** [evcohen/eslint-plugin-jsx-a11y#479]
Hi,

I'm building a modal component that can be closed with the escape key.

The natural place to put the event listener for this is on the container for the modal itself where the aria role is defined - since that is the one within which focus is trapped.

But jsx-a11y complains that this role is non-interactive.

Is this consistent with the w3 docs?

https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

Which states that escape should close the dialog - this would seem to imply that dialogs are interactive?

I'm using v6.03 so I'm a few behind - but I can't see in the release notes that this would be different on the latest version.

If my assumptions are incorrect - any suggestions on best practice approach for this?

**Comment by jessebeach** [comment]
@danhaggard what an interesting little edge case. A `dialog` is not interactive, it's a container. But I can see the logic in putting a key press handler on the container to catch the ESC key press. 

#502 should address this.

**Comment by danhaggard** [comment]
Awesome!  Thanks for the great work @jessebeach

**Comment by y1n0** [comment]
I am on v6.3.1 and I still get a warning on this
