### ISSUE TITLE
`<input type="checkbox" role="switch" />` should pass jsx-a11y/role-has-required-aria-props

### ISSUE THREAD

**Issue by jessebeach** [evcohen/eslint-plugin-jsx-a11y#484]
`<input type="checkbox" role="switch" />` should pass jsx-a11y/role-has-required-aria-props

**Comment by qw-in** [comment]
It is passing for me. Are there any other details? I can submit [this](https://github.com/qw-in/eslint-plugin-jsx-a11y/commit/5f5b745bd54b5fdd639f02ac77b83e1be83f65bc) as a pr anyway if you want
