### ISSUE TITLE
No able to disable rules

### ISSUE THREAD

**Issue by ChrisCPeixoto** [evcohen/eslint-plugin-jsx-a11y#497]
Hi,

I am trying to disable some of the rules which i dont find relevant. But i still get the warning message.
This is my  .eslintrc file 

```
> {
  "extends": "airbnb",
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "mocha": true
  },
  "rules": {
    "react/destructuring-assignment": [0, "always"],
    "jsx-a11y/no-template-curly-in-string": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/click-events-have-key-events": "off"
  }
}
```

**Comment by ljharb** [comment]
no-template-curly-in-string isn’t an a11y rule, it’s a core rule (and it’s always relevant).

as for the others, can you try adding `”root”: true`, and if you’re still seeing warnings, can you provide the exact warning output you’re getting? (Also make sure you don’t have any other eslintrc files in your project)

**Comment by ChrisCPeixoto** [comment]
I removed that first rule that you mentioned wasn't part of the package, and it seems to work now. Thank you
