### ISSUE TITLE
Use <a /> to create interactive elements that can be manipulated by the keyboard

### ISSUE THREAD

**Issue by TongDaDa** [evcohen/eslint-plugin-jsx-a11y#501]
I always use the \<a\/> to wrap some elements such as li, div tag, because that can be manipulated by keyboard and there are blue lines wrapped around the elements, so it's very convenient without me to reproduce the original attributes(outline) of other elements, but when I use your rules, it needs to fill in a meaningful href property. What should I do then?

![screen shot 2018-11-14 at 10 32 50 pm](https://user-images.githubusercontent.com/23241188/48489622-6ee6f600-e85e-11e8-8765-e53b22a46bcc.png)

**Comment by ljharb** [comment]
I’m confused about that technique. If you want visible outlines, you can do that with css. There’s no need to abuse anchor tags for that purpose.

**Comment by TongDaDa** [comment]
@ljharb Ok, How do you solve accessibility problems in peacetime? Can you recommend it to me?

**Comment by ljharb** [comment]
What is “peacetime”?

**Comment by TongDaDa** [comment]
@ljharb  Sorry, that is how do you usually solve it, not peacetime, that is my incorrect typing.

**Comment by ljharb** [comment]
I’m not sure i understand the question. If the user wants to tab to any element - not just focusable ones - on Safari, for example, there’s a preference setting to control that. I’m sure other browsers have similar settings. Additionally, you can add a tabIndex, or a role, or use a number of other techniques to indicate to the browser that an element is tabbable. Can you elaborate on what you’re trying to achieve by wrapping with anchors, and what’s not working when unwrapped?

**Comment by TongDaDa** [comment]
@ljharb Ok, thanks i'm going find other ideal, this would not be formal.

**Comment by jessebeach** [comment]
@TongDaDa wrapping elements in `<a />` to achieve a visual artifact isn't standard practice. This plugin is correctly flagging this practice as it impacts accessible interactions. I'm closing it.
