### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by pierceray** [evcohen/eslint-plugin-jsx-a11y#518]
First off, I really appreciate the time and effort that has been put into this project.  

There have been quite a few updates since the last release in October (6.1.2), when should we expect a new release to drop?

Thanks for all that you do.

**Comment by jessebeach** [comment]
@pierceray I'm feeling it to. It may be time for the next major release soon.

**Comment by ljharb** [comment]
It'd be great to cut a release prior to any major release, so as much nonbreaking stuff as possible can be in the current major :-)

**Comment by evcohen** [comment]
v6.2.1 was released today. Thanks @jessebeach !
