### ISSUE TITLE
Prepping Minor release v6.2.2

### ISSUE THREAD

**Issue by jessebeach** [evcohen/eslint-plugin-jsx-a11y#533]
These are the commits I plan to cherry-pick into a v6.2.2 release...unless we just want to go for a Major V7 :)

`git log v6.1.2..master --oneline`

ead1767 Merge pull request #515 from jessebeach/control-has-associated-label
5650674 [new rule] control-has-associated-label checks interactives for a label
9924d03 document jsx-a11y/label-has-associated-control assert option
fff6a4b Merge pull request #507 from evcohen/greenkeeper/jscodeshift-0.6.0
4d74737 Merge branch 'master' into greenkeeper/jscodeshift-0.6.0
ffa5430 Merge pull request #509 from evcohen/greenkeeper/flow-bin-0.88.0
7fae85a Merge branch 'master' into greenkeeper/flow-bin-0.88.0
8bf4cb5 Merge pull request #513 from evcohen/greenkeeper/emoji-regex-7.0.2
52fd7ea Merge branch 'master' into greenkeeper/emoji-regex-7.0.2
33a1f94 [fix] - Purely decorative emojis do not need descriptions.
4186f91 Merge pull request #508 from greypants/patch-1
29d20f7 fix(package): update emoji-regex to version 7.0.2
0b63f73 chore(package): update flow-bin to version 0.88.0
~~baa1344 Disable jsx-a11y/label-has-for in recommended~~
2c5fb06 chore(package): update jscodeshift to version 0.6.0
e53906d Merge pull request #506 from mahendrakulkarni177/master
87debc0 corrected no-noninteractive-element-to-interactive-role.md file
59240fe Merge pull request #493 from FranklinYu/fix/doc-deprecation
bde7727 Merge branch 'master' into fix/doc-deprecation
7c53b60 Merge pull request #505 from evcohen/greenkeeper/flow-bin-0.87.0
3cce0bc Merge branch 'master' into greenkeeper/flow-bin-0.87.0
878ad19 Merge pull request #504 from othree/master
d56265b chore(package): update flow-bin to version 0.87.0
477966f Update test for implicit role of `img`
f484ce3 No implicit role for `<img>` with `alt=""`
df9ce85 Merge pull request #503 from jessebeach/fix--label-has-associated-control
6c33bcb Add select to the list of default control elements in label-has-associated-control
c0ca0b8 Merge pull request #502 from jessebeach/dialog-is-kind-of-interactive
011f8d9 Dialog and Alert roles can host keyboard listeners
6596435 Merge pull request #500 from ybiquitous/set-plugins-to-configs
0f6a8af More easier `plugin:jsx-a11y/{recommended,strict}` configs
3844248 Mark the replacement for label-has-for
93265cb normalizedValues to values
651366c Make aria-role case sensitive
56d3b9a [484] Fix role-has-required-aria-props for semantic elements like input[checkbox]
46e9abd Handle the type={truthy} case in jsx

**Comment by ljharb** [comment]
A minor would be 6.3; 6.2.2 is a patch release.

I’m actually ok with considering that commit a non breaking change - it will make users see fewer errors, not more.

**Comment by evcohen** [comment]
Published v6.2.0 - I will try and put together the changelog tomorrow.

**Comment by jessebeach** [comment]
@evcohen I'll add the changelog to the PR.

**Comment by evcohen** [comment]
[v6.2.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v6.2.0) published! thanks for everything 😄
