### ISSUE TITLE
Add plugin as part of "plugin:jsx-a11y/recommended"

### ISSUE THREAD

**Issue by silvenon** [evcohen/eslint-plugin-jsx-a11y#538]
Many ESLint plugins add themselves to the configuration as part of `plugin:<name>/recommended` preset. This way people wouldn't have to add `jsx-a11y` to `plugins` when extending recommended rules.

I'll open a PR if you want this.

**Comment by ljharb** [comment]
I consider it a bug if they don’t; a PR to fix it would be great.

**Comment by silvenon** [comment]
I was using an older version of eslint-plugin-jsx-a11y (6.1.2), this has been fixed in the meantime.
