### ISSUE TITLE
Extract AST JSX utils to separate repo/npm module

### ISSUE THREAD

**Issue by evcohen** [evcohen/eslint-plugin-jsx-a11y#54]
Just wanted to start a discussion and see if anyone thought there was value in maybe creating a `jsx-ast-utils` npm module so people can build other cool linting rules surrounding JSX. We can export functions like `getAttribute`, `hasAttribute`, `getAttributeValue`, and `getLiteralAttributeValue`.

I think there's value in keeping it separately maintained but would definitely be more overhead for fixing bugs here and defining a more robust and well defined API for those functions. Thoughts?

**Comment by ljharb** [comment]
@yannickcr would this be something `eslint-plugin-react` could also utilize? I think both of these plugins using a shared AST core would be very helpful.

**Comment by evcohen** [comment]
Well, I created `jsx-ast-utils`

[jsx-ast-utils](https://github.com/evcohen/jsx-ast-utils)

Think it will help with expanding, testing, and writing more robust rules

**Comment by yannickcr** [comment]
@ljharb That's totally something we could use 👍
