### ISSUE TITLE
anchor-is-valid - why <a href="#" /> is Invalid ?

### ISSUE THREAD

**Issue by zcs19871221** [evcohen/eslint-plugin-jsx-a11y#555]
question with rules : anchor-is-valid 

why `<a href="#" />`  is Invalid ?
it just make navigation . and i just use it to jump to the top of page. please teach me, thanks

**Comment by ljharb** [comment]
You can use `#top` for that.

**Comment by SalTor** [comment]
First, the href needs a specific target. AKA, which element with a blank ID are you targeting? Probably none, so place an element with, say, id="top" at the beginning of your page.

Second, anchor tags need contents, as described by the `jsx-a11y/anchor-has-content` linting rule

**Comment by ljharb** [comment]
You don’t need an element; all browsers send `#top` to the same place as `#`.

**Comment by SalTor** [comment]
Thanks @ljharb ! Good to know

**Comment by ljharb** [comment]
To answer the original question; it's because `#` is almost exclusively abused to make a link that doesn't actually go anywhere, so they can add JS behavior. `#top`, at least, is explicit.
