### ISSUE TITLE
jsx-a11y/anchor-is-valid detects link as invalid if it starts with the word #javascript

### ISSUE THREAD

**Issue by anthony0030** [evcohen/eslint-plugin-jsx-a11y#579]
The below exaple triggers a warning:
`<a href="#javascriptComponents" >
  javascript Components
</a>`

**Comment by ljharb** [comment]
If that gives a warning and `#somethingelse` doesn’t, then this is a bug.

**Comment by anthony0030** [comment]
error:
#javascripComponents
#javascript
#javascriptCheesecake
#javascriptPleaseNoError

no error:
#javascripComponents (without the letter t)
#javascrip (without the letter t)
#somethingelse
#theJavascriptCheesecake
#Javascript (capital letter J)
#javAscript (capital letterA)
