### ISSUE TITLE
Assigning a constant in `role` on  interactive elements throws error.

### ISSUE THREAD

**Issue by gauravksoni** [evcohen/eslint-plugin-jsx-a11y#583]
StackOverFlow link
https://stackoverflow.com/questions/55624906/assigning-role-to-interactive-elements-via-constant

**Comment by ljharb** [comment]
There’d be no way for a linter to know the value of the constant statically. What’s your use case?

**Comment by gauravksoni** [comment]
I have a set of `role` constants defined and wanted to use that. Rather than writing "some role" every time i prefer to have a set of constants defined and use those for assigning role.

**Comment by ljharb** [comment]
why? What’s the benefit, given that this linter rule can ensure correctness if you write it inline?

**Comment by jessebeach** [comment]
Probably addressed in #607.
