### ISSUE TITLE
Add peerDependency on eslint

### ISSUE THREAD

**Issue by ljharb** [evcohen/eslint-plugin-jsx-a11y#62]
Since this package implicitly depends on eslint, it should be a peer dep.

**Comment by evcohen** [comment]
Thanks, fixed in [v1.5.4](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/1.5.4)

**Comment by ljharb** [comment]
@evcohen thanks - could you also add `|| 3.x` so that it works with eslint 3?

**Comment by evcohen** [comment]
Done! [v1.5.5](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/1.5.5)

**Comment by ryanvanoss** [comment]
@evcohen, that should have been a major bump -- what used to work when using ESLint ^1.0.0 now fails due to the explicit peer dependency declaration. I thought I taught you better ;)

**Comment by ljharb** [comment]
I'd have thought it'd have failed on eslint v1 a long time ago - indeed that would make it a major bump, even though nobody should still be on v1 ;-)

**Comment by ryanvanoss** [comment]
@ljharb, yep, it would have if we had been working on the old repo -- just picked up some old work from the end of last year. Definitely time to upgrade.

**Comment by evcohen** [comment]
miss you @ryanvanoss 
glad i can still create bugs for you guys 😜

**Comment by ryanvanoss** [comment]
@evcohen we never doubted. Thanks for living up to expectations :P
