### ISSUE TITLE
`heading-has-content`: dangerouslySetInnerHTML should pass

### ISSUE THREAD

**Issue by ljharb** [evcohen/eslint-plugin-jsx-a11y#64]
`<h1 dangerouslySetInnerHTML={{ __html: 'foo' }} />` should pass, since the heading has content.

**Comment by ljharb** [comment]
Any update on this one?

**Comment by evcohen** [comment]
@ljharb will work on this today.

**Comment by evcohen** [comment]
Is your example correct/shorthand for `<h1 dangerouslySetInnerHTML={{ __html: 'foo' }} />`?

**Comment by ljharb** [comment]
oh oops, sorry, i retyped my example from memory. I'll update the description.

**Comment by evcohen** [comment]
[v2.0.1](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/2.0.1) published with fix. Thanks 😄
