### ISSUE TITLE
Please remove validity warning on href="#"

### ISSUE THREAD

**Issue by maniac0s** [evcohen/eslint-plugin-jsx-a11y#645]
I got this warning in my ReactJS application:

> ./src/components/TemplateListItem.js Line 16:17: The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md

The hyperlink looks as following:

`<a href="#" role="tab" data-rb-event-key="1" id="main_tabs-tab-1" aria-controls="main_tabs-tabpane-1" aria-selected="true" class="nav-item nav-link active">Top</a>`

href="#" is a valid anchor (meaning "Scroll to top of page").

https://stackoverflow.com/a/21397285/6329530

**Comment by ljharb** [comment]
You can use `#top` for that; it works in every browser that `#` works in. That's more explicit, and doesn't overlap with the common pattern of using `#` to abuse an anchor for non-link-like behavior.

**Comment by maniac0s** [comment]
Why use "#top" when "#" officially means "top" already?

**Comment by ljharb** [comment]
Because `#` is abused to make anchors behave like buttons, `#top` is not.

**Comment by maniac0s** [comment]
So people will just use "#top" instead, where is the difference? 

href="#" is a valid value. The warning says it is not, which is false.

**Comment by ljharb** [comment]
It's not a navigable URL, which is what the warning says.

**Comment by maniac0s** [comment]
...

The a - tag stands for "anchor" which can be an external resource or an _anchor_ on the same page. According to w3c "#" stands for "top of page". This is the official **standard**, no matter what you say. Having "#" in href is **valid**.

**Comment by ljharb** [comment]
It is valid, but the intent of the rule is to make it invalid, no matter what any spec says.

**Comment by maniac0s** [comment]
And there I thought linter supposed to follow the official standards not create their own at whim.

**Comment by ljharb** [comment]
Nope, linters are 100% about creating their own standards "at whim" - the *engines* follow the official standards.

**Comment by maniac0s** [comment]
Yeah this still makes no sense but you do you I will continue to just ignore this warning because it's bullshit.

**Comment by gaurav5430** [comment]
@ljharb 

I regularly use links with href="#" with javascript to take the user to another page. So, it still performs a navigation, not an action, just that navigation is taken care of by javascript.
This is due to the fact that either the href is not available before the link is clicked, or i need to send some more info to the next page using the history state.

https://stackoverflow.com/questions/63451798/accessibility-javascript-only-links-with-href-an-antipattern
https://stackoverflow.com/questions/63251705/accessibility-using-javascript-only-links-with-href

Does this above requirement satisfy the use case for a button and not a link?

**Comment by ljharb** [comment]
@gaurav5430 it's highly inaccessible to do that; navigation should never be performed by JS. That also breaks "add to favorites" and "open in new tab" and a ton of other things. If the href isn't available, it shouldn't be an `<a>`, and if you need to send more info, it should be a form submission.

I don't agree with those SO answers that `href="#"` is ever a good idea.

**Comment by gaurav5430** [comment]
Some valid points. 

Do you think window.open should always happen from a form submission then? 
And a button should never be used for navigation?
For example, Is it then on to scroll to another part of the page on button click vs using an anchor to do the same?

**Comment by ljharb** [comment]
No, I think it should never happen from a form submission - a form submission navigates the current page.

Yes, there is an existing element for navigation, `<a>`, and that's the only thing that should provide navigation.

Scrolling to an anchor (`#foo`, eg) is navigation.

**Comment by ljharb** [comment]
My suggestion is to not rudely force a new page on a user - every browser has a built-in way to open something in a new page - ie, just use a normal link.

**Comment by gaurav5430** [comment]
I don't understand. Are you suggesting there is no valid use case for window.open?

All I meant to ask was, If there is a valid use case for window.open, should it happen on click of a button or on a link? Is it an action or a navigation ?

**Comment by ljharb** [comment]
Yes, that's what I'm suggesting.

If there were one, I'd use `<a target="_blank" href="a real URL">`.
