### ISSUE TITLE
role-has-required-aria-props being applied to react components

### ISSUE THREAD

**Issue by majapw** [evcohen/eslint-plugin-jsx-a11y#65]
We are trying to build a React component that takes in aria-props and passes them down to a child `<input />` element. Thus, we have properties on our component like `ariaAutocomplete`, `ariaExpanded`, `ariaOwns`, etc.

However, we can't add a `role` prop because when we try to assign  `role="combobox"` to the React component to be passed down, we end up triggering this rule because we are using `ariaExpanded` and not `aria-expanded` at this level.

Would it be possible to limit this rule to DOM level elements?

**Comment by lencioni** [comment]
Alternatively, what do you think about checking for kebab-case ARIA props on DOM components and camelCase ARIA props on non-DOM components?

**Comment by ljharb** [comment]
I think that instead, the attributes on the wrapper should be `expanded`, not `ariaExpanded`, for example. The wrapper should be abstracting around the dom element - iow, the wrapper IS the dom element conceptually. So when i’m using the wrapper, I shouldn’t know or care what’s inside it - and i’m assigning aria props as if that’s the leaf node, and an "aria" prefix makes that abstraction leaky.

**Comment by evcohen** [comment]
@ljharb i agree with encapsulating `aria` props to the low-level DOM component, however couldn't this cause collisions with props that have different semantic meaning than the `aria` prop itself (i.e. `owns` could be a prop that could mean something totally different than what `aria-owns` means in the context of the application)

We can just add a config setting for user to note his/her convention for wrapper components

**Comment by ljharb** [comment]
It might make sense for all aria rules to only ever touch DOM components by default, and have config options both for conventions, and for which components (like `Input`, for example) the rules should apply to? It seems like some rules behave this way but some do not.

**Comment by evcohen** [comment]
Yeah that makes sense, it just makes sharing configs shitty as people have different naming conventions for components. People who use `eslint-config-airbnb` would have to override all of these rules to apply the right component name to the config, which sucks.

It probably makes sense to have default mappings of _probable_ wrapper components (`input` => `Input`, `Image` => `img`) and just go through a series of checks:

1. First check for camelCase
2. Then check for prop without `aria`
3. If neither, then warn.

**Comment by ljharb** [comment]
Perhaps it would be better to use global config "settings", rather than per-rule configs for this? That way, all aria rules could read from the same settings value. `eslint-plugin-import` uses this to configure module extension resolution, for example.

**Comment by evcohen** [comment]
Closing this and filing a new ticket to track global settings. Still think that this is important to move forward on a couple of rules
