### ISSUE TITLE
[label-has-for] Not needed if it contains a form control?

### ISSUE THREAD

**Issue by tleunen** [evcohen/eslint-plugin-jsx-a11y#67]
I wonder if this rule is really necessary if the input is inside the label (which is valid)?

I believe that for a11y, the `for` attribute is not required if the label contains a form control.

**Comment by ljharb** [comment]
It's still necessary - something like 95% of devices work with "wrapped" and a different 95% work with "for/id-linked" - so the best is to always have both.

**Comment by evcohen** [comment]
This is a duplicate of #51 - will update documentation to further explain

**Comment by tleunen** [comment]
Oh my bad, sorry about that. Closing it now.

**Comment by evcohen** [comment]
No worries 😄 hope that helped!
