### ISSUE TITLE
change errors to filename:line:col format?

### ISSUE THREAD

**Issue by Pomax** [evcohen/eslint-plugin-jsx-a11y#675]
One of the nice things about VS Code (and other editors) is that a line that uses the `${file path}:${line number}:${colum}` format can immediately be jumped to, whereas the current format of giving the filename but then line/col as separate entries means there is no way to immediately jump to the offending line. 

Is there a way to make this plugin output "direct-resolvable" errors?

**Comment by ljharb** [comment]
Output is part of eslint itself, and plugins have no control over it.

You can use a custom formatter, or you can file an issue/PR/RFC on eslint itself.

**Comment by Pomax** [comment]
gotcha, thanks!
