### ISSUE TITLE
Rule label-has-associated-control shows when input inside label

### ISSUE THREAD

**Issue by Yegorich555** [evcohen/eslint-plugin-jsx-a11y#680]
Rule checking is wrong. According to **label-has-associated-control.md**

> This rule checks that any label tag (or an indicated custom component that will output a label tag) **either** (1) wraps an input element (or an indicated custom component that will output an input tag) **or** (2) has an htmlFor attribute and that the label tag has text content.

But checking is wrong with the following code:

```jsx
export function Test() {
  return (
  // Error: A form label must be associated with a control. eslint(jsx-a11y/label-has-associated-control)
    <label>
      <input />
    </label>
  );
}
```
![image](https://user-images.githubusercontent.com/25006810/79583666-0bf23200-80d6-11ea-881e-00ae57f47a6f.png)

**Comment by ljharb** [comment]
imo it's not wrong - labels and inputs must BOTH be nested and for-ID linked for full a11y coverage. 

By default, the rule accepts either one - how is your rule configured? The airbnb config, for example, requires both.

**Comment by Yegorich555** [comment]
Default **either one** doesn't work. By default I have **both**. I use [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) that includes this plugin. And I don't have any redefined rules.
Why do I think rule is not correct? Because [label-has-associated-control.md](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md) has **either one** but default of the rule is **both**.

Do you think **both** is a good practice? Input can be inside label for avoiding id-references that sometimes headache to control unique. So imo **both** is redundant (even useless) practice.

**Comment by ljharb** [comment]
The airbnb config sets the rule to use both, because yes, I think both is a good practice. It's not redundant, because there are some assistive devices that only support nesting, and others that only support linking - thus, to truly be *accessible* to all, one must do both.

**Comment by Yegorich555** [comment]
Ok. Thanks for explanation.
