### ISSUE TITLE
Adding options to image-redundant-alt

### ISSUE THREAD

**Issue by badtant** [evcohen/eslint-plugin-jsx-a11y#72]
Hi,

I'm trying to do a pull request which add options to image-redundant-alt so that it can cater for any words the user wants. How do I add words to be included in the tests so that I can see that it's working when I run them? I tried to add it in src/index.js but when I log context.options it's empty.

Thanks

**Comment by evcohen** [comment]
Check out `tests/src/rules/img-has-alt.js`. The object takes an argument called `options` which reflects `context.options`. You then have to update the schema in the `img-redundant-alt` rule to accept those options! 

Cool idea, let me know if you have any other questions.
