### ISSUE TITLE
Button with child label

### ISSUE THREAD

**Issue by kevinSuttle** [evcohen/eslint-plugin-jsx-a11y#74]
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md

Example: 
```jsx
const LabelButton = (props:LabelButtonProps) =>
  <Button design={props.design} onClick={props.onClick}>
    <label>{props.label}</label> {/* 'htmlFor' Linter error thrown here */}
  </Button>
```

Is this an anti-pattern?

**Comment by ljharb** [comment]
i'm not sure why a button needs a label, but yes, the button would need an ID, and the label would need to enclose the button and have an `htmlFor` that points to it.

**Comment by kevinSuttle** [comment]
Use case: A button would need a label if say, there were only an icon.

**Comment by ljharb** [comment]
Why wouldn't you just make it not only be an icon? Icons should always have accompanying text, and ideally inside the clickable region since small target areas are problematic for, say, people with arthritis.

**Comment by kevinSuttle** [comment]
Because it still needs button behavior. It's getting a title via `aria-labelled-by`, and the icon's title is in the SVG along with the graphics.

**Comment by ljharb** [comment]
So the title is impossible-to-translate image-based text? O.o

**Comment by kevinSuttle** [comment]
What? No. 

https://egghead.io/lessons/css-accessible-icon-buttons

**Comment by ljharb** [comment]
Right - so typical users won't see any text, just an icon. That doesn't seem very UX-friendly to me :-/

Either way, I'd expect the label to wrap the button, not the other way around.
