### ISSUE TITLE
Rule proposal: require clickable non-button/non-link elements listen for space or enter

### ISSUE THREAD

**Issue by lencioni** [evcohen/eslint-plugin-jsx-a11y#77]
If you are making a non-button or non-link element clickable, you also need to wire up keyboard listeners for space and enter. While I don't think we will be able to ensure that this is all implemented correctly, we can likely at least add a warning for any DOM element that is not `a` or `button` that has `onClick` and not a keyboard event listener.

cc @backwardok

**Comment by backwardok** [comment]
Btw I think also inputs work as well - essentially form elements and links should have that behavior default. It's the elements that you're adding non default behavior to where you have to also add in keyboard listeners

**Comment by lencioni** [comment]
Oh right, of course.

**Comment by ljharb** [comment]
For purposes of semantic markup, why would we want to encourage adding `onClick` to a non-natively-clickable thing anyways?

**Comment by lencioni** [comment]
Yeah, it should likely suggest using a button or link first, or alternatively adding the keyboard stuff.

**Comment by ljharb** [comment]
Do we have another rule that can actively prohibit adding interaction behavior to non-natively-interactable DOM elements?

**Comment by evcohen** [comment]
> Do we have another rule that can actively prohibit adding interaction behavior to non-natively-interactable DOM elements?

No but we have  [onclick-has-role](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/onclick-has-role.md), which requires adding the `role` prop to non-natively-interactable DOM elements with click handlers.

*********

just to clarify, this seems like we are taking the logic for determining non-interactive DOM elements from `onclick-has-role` and enforcing that those elements with `onClick` handlers have accompanying `onKeyDown`, `onKeyUp`, or `onKeyPress` props.

rule: `click-events-have-key-events` (similar to [mouse-events-have-key-events](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/mouse-events-have-key-events.md))

**Comment by ljharb** [comment]
I filed #78 for https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/77#issuecomment-241918479
